### ISSUE TITLE
Experiment Todo

### ISSUE THREAD

**Issue by ffatchen** [ffatchen/NNF#1]
- [x] Rejected percentile relative to accepted distribution histograms 
- [ ] Rejected percentile relative to accepted distribution tables (binned at 5%)
- [x] Box and whiskers to look at range of scores over years and types
- [x] Mean reapplication: 0.44 (aggregate), 0.40 (female), 0.48 (male), 0.35 (age <40), 0.51 (age>=40)
- [x] Budget histogram for each type of call
- [x] Update power analysis
- [ ] Update slides w/ new figures and tables
- [ ] Summary stats for all self reported variable: mean, med, mode and missing or incoherent variables 
- [ ] Overlapping distributions: 75% and accepted (for everyone, gender, split by instrument type and year, etc.) 
- [ ] Accepted distributions by gender 
- [ ] Variation across instruments
- [ ] Update power link 
- [ ] Update power by gender and career stage (postdocs and everyone else; median split)
- [ ] Update power with people who varying people
- [ ] Histogram of all applicants age
- [ ] Histogram of age split by application status
- [ ] Budget figures

**Comment by ffatchen** [comment]
@haribala03 
- [ ] Add labels to each figure (see the instrument types for example of what this should look like)
- [ ] Use a loop for the gender figures (see instrument types for example) 
Let's leave age for now we need to recreate this variable based off the declared position i.e. postdoc, AP etc. 

- [ ] Generate histogram of ages across all grants use a pastel color for the fill (not green or red) 
- [ ] Histogram of age split by application status use two pastel colors again not green or red
